# ─────────────────────────────────────────────────────────────────────────────
# comment.py  —  AI LinkedIn commenting for profile warmth & visibility
#
# Strategy: find posts by ICP-matching people, generate genuine comments,
# let user approve, then post via Playwright. Max 5 comments/day.
#
# Safety by design:
#   - Max 5 comments/day (far below LinkedIn's limits)
#   - 3+ minute gaps between comments
#   - User must approve every comment before it's posted
#   - Genuine, non-salesy comments generated by Claude
#   - Session cookies refreshed and saved after every browser run
# ─────────────────────────────────────────────────────────────────────────────
import time
import random
import logging
import json
import re

log = logging.getLogger(__name__)

MAX_COMMENTS_PER_DAY    = 5
MIN_GAP_SECONDS         = 240   # 4 minutes minimum between comments
MAX_GAP_SECONDS         = 720   # 12 minutes maximum — wide randomness looks human
MAX_COMMENTS_PER_RUN    = 2     # Never blast all 5 at once — spread through the day

# Matches linkedin_client.py — required to avoid bot detection
_USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/131.0.0.0 Safari/537.36"
)
_PLAYWRIGHT_ARGS = [
    "--no-sandbox",
    "--disable-blink-features=AutomationControlled",
    "--disable-infobars",
    "--disable-dev-shm-usage",
]

# ── Anti-detection JavaScript ─────────────────────────────────────────────────
# Injected into every page BEFORE LinkedIn JS runs.
# Patches the most common bot-detection signals used by LinkedIn's risk engine.
_ANTI_DETECT_JS = """
// 1. navigator.webdriver — THE #1 signal. Playwright sets this to true by default.
Object.defineProperty(navigator, 'webdriver', { get: () => undefined });

// 2. window.chrome — headless Chromium is missing chrome.runtime entirely.
if (!window.chrome) {
    window.chrome = { runtime: { onConnect: {addListener:()=>{}}, onMessage: {addListener:()=>{}} } };
}

// 3. navigator.plugins — headless has 0 plugins; real Chrome has at least 3.
Object.defineProperty(navigator, 'plugins', {
    get: () => {
        const arr = [
            {name:'Chrome PDF Plugin', filename:'internal-pdf-viewer'},
            {name:'Chrome PDF Viewer', filename:'mhjfbmdgcfjbbpaeojofohoefgiehjai'},
            {name:'Native Client',     filename:'internal-nacl-plugin'},
        ];
        arr.length = arr.length;
        return arr;
    }
});

// 4. navigator.languages — headless sometimes returns [] or just ['en'].
Object.defineProperty(navigator, 'languages', { get: () => ['en-AU', 'en-GB', 'en'] });

// 5. navigator.permissions — headless returns 'denied' for notifications by default.
const _origPermQuery = window.navigator.permissions.query.bind(navigator.permissions);
window.navigator.permissions.query = (p) =>
    p.name === 'notifications'
        ? Promise.resolve({ state: Notification.permission })
        : _origPermQuery(p);

// 6. WebGL strings — headless returns 'Google SwiftShader' / 'Mesa' which is flagged.
try {
    const _getParam = WebGLRenderingContext.prototype.getParameter;
    WebGLRenderingContext.prototype.getParameter = function(p) {
        if (p === 37445) return 'Intel Inc.';
        if (p === 37446) return 'Intel Iris Pro OpenGL Engine';
        return _getParam.call(this, p);
    };
} catch(e) {}

// 7. Hide automation-related object keys from toString checks.
const _origHasOwnProp = Object.prototype.hasOwnProperty;
Object.prototype.hasOwnProperty = function(prop) {
    if (prop === 'webdriver') return false;
    return _origHasOwnProp.call(this, prop);
};
"""


def _count_comments_today(state: dict) -> int:
    from datetime import datetime, timezone
    today = datetime.now(timezone.utc).date().isoformat()
    return sum(
        1 for c in state.get("posted_comments", [])
        if (c.get("posted_at") or "")[:10] == today
    )


def _strip_emojis(text: str) -> str:
    """Remove emoji characters from text as a safety net."""
    import re
    # Remove all emoji/symbol unicode ranges
    emoji_pattern = re.compile(
        "[\U00010000-\U0010ffff"   # supplementary multilingual plane (most emojis)
        "\U0001F600-\U0001F64F"   # emoticons
        "\U0001F300-\U0001F5FF"   # symbols & pictographs
        "\U0001F680-\U0001F6FF"   # transport & map
        "\U0001F1E0-\U0001F1FF"   # flags
        "\U00002702-\U000027B0"   # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub("", text).strip()


# Phrases that instantly signal AI — banned from all generated text
_NO_AI_PHRASES_RULE = """
STRICT rules — these instantly reveal AI authorship, never use them:
- NO em dashes (—). This is the #1 AI tell. Use a period or a comma instead. Rewrite the sentence if needed.
- NO emojis of any kind
- NO "Absolutely", "Certainly", "Great question", "Great point", "Great insight"
- NO "This resonates", "Couldn't agree more", "Love this", "So true"
- NO "particularly compelling", "genuinely rare", "incredibly important", "truly fascinating"
- NO "what makes this X is", "the tension between X and Y"
- NO "I hope this finds you well", "Feel free to reach out"
- NO hashtags
- NO buzzwords: leveraging, synergy, game-changer, revolutionize, streamline, utilize, impactful
- NO "It's worth noting", "It goes without saying", "At the end of the day", "In today's landscape"
- NO long sentences with multiple clauses — keep it short and punchy
- NO exclamation marks used just to seem enthusiastic
Write like a real human texting a smart peer — plain words, short sentences, direct."""


def generate_comment(post_text: str, poster_name: str, offering: str) -> str:
    """Use Claude to write a genuine, non-salesy comment on a LinkedIn post."""
    import anthropic
    import os
    from config import ANTHROPIC_API_KEY

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    # Load knowledge base for voice/specificity
    _kb = {}
    _kb_file = os.path.join(os.path.dirname(__file__), "knowledge_base.json")
    try:
        import json as _j
        with open(_kb_file) as _f:
            _kb = _j.load(_f)
    except Exception:
        pass

    voice_notes = _kb.get("brand_voice_notes", "")[:400] if _kb else ""
    core_beliefs = _kb.get("core_beliefs", [])
    beliefs_block = ("\n".join(f"- {b[:120]}" for b in core_beliefs[:3])) if core_beliefs else ""

    # Load saved comment style instructions if they exist
    _style_file = os.path.join(os.path.dirname(__file__), "prompts", "comment_style.txt")
    try:
        with open(_style_file, "r") as _f:
            _style_instructions = _f.read().strip()
    except Exception:
        _style_instructions = ""

    style_block = (
        f"\nAdditional style instructions:\n{_style_instructions}\n"
        if _style_instructions else ""
    )

    kb_block = ""
    if voice_notes or beliefs_block:
        kb_block = "\nVoice and worldview to draw from:\n"
        if voice_notes:
            kb_block += f"Voice: {voice_notes}\n"
        if beliefs_block:
            kb_block += f"Core beliefs (use as source of insight when relevant):\n{beliefs_block}\n"

    prompt = f"""You are Ermo, founder of Authentik Studio — brand documentary and video production for B2B founders.
Your edge: you understand the credibility gap. Expert founders do exceptional real-world work but their online presence doesn't reflect it. You've seen this cost founders deals they never even knew they lost.
{kb_block}
A LinkedIn post from {poster_name}:
---
{post_text[:800]}
---
{style_block}
{_NO_AI_PHRASES_RULE}

Write a SHORT (2-3 sentences), genuine comment that:
- Picks ONE specific point from the post and engages with it directly
- Adds a sharp, specific observation or insight — something that makes the poster think "this person really gets it"
- Sounds like a thoughtful peer, not a marketer or fan
- NEVER mentions Authentik Studio, your services, or anything salesy
- Can end with ONE genuine question if it fits naturally — something that opens a real conversation
- Short sentences. No em dashes. No exclamation marks. No emojis.
- The comment should make other readers want to click your name to see who said that

The goal is to be the most interesting voice in the comments — someone with a real point of view — not to pitch anything.

Reply with ONLY the comment text. No quotes, no explanation, no preamble."""

    try:
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",  # Haiku: 5x cheaper, fine for short comments
            max_tokens=150,
            messages=[{"role": "user", "content": prompt}],
        )
        return _strip_emojis(resp.content[0].text.strip())
    except Exception as e:
        log.error(f"Comment generation failed: {e}")
        return ""


def _score_post_relevance(posts: list, offering: str) -> list:
    """
    Use Claude Haiku to score each post 1-10 for relevance to the offering.
    Posts scoring < 5 are tagged low_relevance=True so the UI can warn the user.
    Batches all posts into one API call to keep costs near zero.
    """
    if not posts:
        return posts
    import anthropic
    from config import ANTHROPIC_API_KEY

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    offering_line = offering[:250].split("\n")[0].strip()

    snippets = "\n".join(
        f"{i+1}. [{p['poster_name']}] {p['post_text'][:120]}"
        for i, p in enumerate(posts)
    )

    prompt = f"""You score LinkedIn posts for how valuable it would be for Ermo (founder of Authentik Studio — brand documentary and video production for B2B founders) to leave a thoughtful comment.

High-value targets (score 8-10):
- B2B founders, consultants, agency owners, coaches posting about: content not working, LinkedIn growth, brand/visibility struggles, credibility, trust, sales cycles, video content
- People with 5K-100K followers in B2B professional services where a sharp comment gets noticed
- Posts about the "credibility gap" between expertise and online presence (even without using that phrase)
- Founders discussing what content strategy they're trying or failing at

Medium value (score 5-7):
- Adjacent topics: thought leadership, personal branding, B2B marketing, founder storytelling
- People who ARE the ICP but the post topic is less directly relevant

Low value — score 1-4 and DO NOT recommend:
- Job seekers, students, HR/recruitment tips, corporate PR, sustainability reports, VA/freelancer content
- Generic motivational posts with no specific angle to engage with
- People who clearly sell competing video/content services (they're not buyers)
- Posts that are pure self-promotion with nothing to respond to

Posts:
{snippets}

Reply ONLY with a JSON array of integers in order. Example: [8,4,7,6,2]"""

    try:
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=100,
            messages=[{"role": "user", "content": prompt}],
        )
        import re as _re2
        raw = resp.content[0].text.strip()
        raw = _re2.sub(r"^```[a-z]*\n?", "", raw)
        raw = _re2.sub(r"\n?```$", "", raw)
        scores = json.loads(raw)
        for i, post in enumerate(posts):
            score = scores[i] if i < len(scores) else 5
            post["relevance_score"] = score
            post["low_relevance"] = score < 5
        log.info(f"Relevance scores: {scores}")
    except Exception as e:
        log.warning(f"Relevance scoring failed ({e}) — all posts kept unscored")
        for post in posts:
            post["relevance_score"] = 5
            post["low_relevance"] = False

    # Sort: high relevance first, but keep all (user decides what to skip)
    posts.sort(key=lambda p: p.get("relevance_score", 5), reverse=True)
    return posts


def _search_for_posts(keywords: list, count: int = 15) -> list:
    """
    Use Brave Search API to find recent LinkedIn posts matching keywords.
    Implements a TIERED engagement strategy:

      Tier 1 — Watering holes (aim for ~60-70% of results)
        Mid-tier creators (5K-50K followers) who talk about B2B growth,
        founder content, LinkedIn strategy. Their *audience* is Ermo's ICP.
        Commenting here puts Authentik Studio in front of warm buyers.

      Tier 2 — Adjacent peers (aim for ~20%)
        Brand strategists, copywriters, B2B coaches serving the same audience.
        Not competitors — parallel services. Good for network cross-pollination.

      Tier 3 — ICP direct (aim for ~10%)
        Founders actively posting about content struggles, visibility gaps,
        credibility problems. Direct proof-of-pain posts.

    Returns list of {post_url, post_text, poster_url, poster_name, tier, tier_reason}.
    """
    try:
        from config import BRAVE_SEARCH_API_KEY
        if not BRAVE_SEARCH_API_KEY:
            log.info("No Brave API key set — skipping search-based post scan.")
            return []

        import urllib.request, urllib.parse, json as _json, re as _re, gzip

        # Common English words used to detect non-English posts
        _EN_WORDS = {
            'the','and','is','in','to','of','a','that','this','with','for','are','was',
            'it','on','be','at','by','have','from','or','an','but','not','what','all',
            'were','when','we','there','can','your','which','their','said','if','do',
            'will','each','about','how','up','out','then','them','so','its','would',
            'make','time','has','more','go','no','way','could','these','into','than',
            'some','very','after','too','most','also','been','over','people','just',
            'because','think','see','did','get','may','still','any','new','our','use',
            'who','know','now','even','both','work','first','year','good','here',
            'need','great','one','i','my','me','we','you','he','she','they','his',
            'her','their','our','its','him','them','us',
        }

        def _is_english(text: str) -> bool:
            """Return True if the text appears to be primarily English."""
            words = set(_re.findall(r'\b[a-z]{2,}\b', text.lower()))
            if not words:
                return False
            en_ratio = len(words & _EN_WORDS) / len(words)
            return en_ratio >= 0.08  # at least 8% of unique words are common English words

        def _brave_search(q: str, freshness: str = "pw") -> list:
            """Run one Brave search with exponential backoff on 429 rate-limit errors."""
            u = (
                "https://api.search.brave.com/res/v1/web/search"
                f"?q={urllib.parse.quote(q)}&count=20&freshness={freshness}"
            )
            req = urllib.request.Request(u, headers={
                "Accept": "application/json",
                "Accept-Encoding": "gzip",
                "Accept-Language": "en-US,en;q=0.9",
                "X-Subscription-Token": BRAVE_SEARCH_API_KEY,
            })
            max_retries = 4
            wait = 5  # seconds — doubles each retry: 5 → 10 → 20 → 40
            for attempt in range(max_retries):
                try:
                    with urllib.request.urlopen(req, timeout=12) as resp:
                        raw = resp.read()
                        if resp.headers.get("Content-Encoding") == "gzip":
                            raw = gzip.decompress(raw)
                        return _json.loads(raw).get("web", {}).get("results", [])
                except urllib.error.HTTPError as e:
                    if e.code == 429:
                        retry_after = int(e.headers.get("Retry-After", wait))
                        sleep_for = max(retry_after, wait)
                        log.warning(
                            f"Brave API rate-limited (429). "
                            f"Waiting {sleep_for}s before retry {attempt+1}/{max_retries-1}…"
                        )
                        if attempt < max_retries - 1:
                            time.sleep(sleep_for)
                            wait *= 2  # exponential backoff
                        else:
                            log.error("Brave API still rate-limited after all retries — skipping query.")
                            return []
                    else:
                        log.warning(f"Brave API HTTP error {e.code} for query '{q}': {e}")
                        return []
                except Exception as e:
                    log.warning(f"Brave API request failed for query '{q}': {e}")
                    return []
            return []

        def _parse_result(r: dict) -> dict | None:
            """Parse one Brave result into a post dict, or None if it should be skipped.

            Only accepts individual LinkedIn /posts/ URLs where we can extract a real
            person's profile slug.  Pulse articles (/pulse/) and feed updates are skipped
            because they belong to company pages, the author is ambiguous, and they often
            redirect to a login wall for the post visitor.
            """
            post_url = r.get("url", "")
            if "linkedin.com" not in post_url:
                return None

            # ── Only individual posts — no pulse / company / feed URLs ────────
            # linkedin.com/posts/<profile-slug>_<activity-id>
            if "linkedin.com/posts/" not in post_url:
                return None

            # Extract profile slug (everything before the first underscore)
            m = _re.search(r'linkedin\.com/posts/([A-Za-z0-9][A-Za-z0-9\-]+?)(?:_|$)', post_url)
            if not m:
                return None
            profile_slug = m.group(1)

            # Profile slug must look like a person handle (2–40 chars, no digits only)
            if not profile_slug or len(profile_slug) < 2 or len(profile_slug) > 40:
                return None
            if _re.fullmatch(r'\d+', profile_slug):
                return None  # numeric IDs = company pages

            profile_url = f"https://www.linkedin.com/in/{profile_slug}/"

            # Post text — try description then extra_snippets
            post_text = r.get("description", "")
            if not post_text:
                snippets = r.get("extra_snippets", [])
                post_text = snippets[0] if snippets else ""

            # Author name from page title
            # Expected formats: "First Last on LinkedIn: …"  or  "First Last | LinkedIn"
            title = r.get("title", "")
            name = ""
            if " on LinkedIn" in title:
                name = title.split(" on LinkedIn")[0].strip()
            elif " | LinkedIn" in title:
                candidate = title.split(" | LinkedIn")[0].strip()
                # Reject if candidate looks like an article headline (> 5 words)
                if len(candidate.split()) <= 5:
                    name = candidate

            # Fallback: humanise the profile slug — but only if it looks like a real name
            if not name and profile_slug:
                parts = profile_slug.replace("-", " ").split()
                # Real names rarely have more than 4 parts
                if 1 <= len(parts) <= 4:
                    name = " ".join(p.title() for p in parts)

            if not name or not post_text or len(post_text) < 50:
                return None

            # Reject names that look like article titles (contain common headline words)
            _HEADLINE_WORDS = (
                "dominates", "results", "queries", "strategy", "marketing",
                "report", "reveals", "survey", "study", "guide", "how to",
                "top ", " best ", " vs ", " vs.", "2024", "2025", "2026",
            )
            if any(w in name.lower() for w in _HEADLINE_WORDS):
                log.info(f"Skipping — name looks like article title: {name!r}")
                return None

            # Skip useless Brave placeholders (private/login-walled posts)
            _USELESS = (
                "we cannot provide a description", "sign in to view",
                "join linkedin", "log in or sign up",
                "by clicking continue to join or sign in",
                "agree to linkedin's user agreement",
                "sign in or create", "login to view", "to view this post",
                "you must be signed in", "linkedin respects your privacy",
            )
            if any(u in post_text.lower() for u in _USELESS):
                return None

            # Skip ads and job postings
            _SKIP = ("sponsored", "advertisement", "job posting", "hiring", "we are hiring",
                     "we're hiring", "open to work", "apply now")
            if any(s in post_text.lower() for s in _SKIP):
                return None

            # Skip old posts (snippet contains age marker like "1y" "2y" etc.)
            age_match = _re.search(r'\b([1-9][0-9]*y)\b',
                                   r.get("description", "") + title)
            if age_match:
                log.info(f"Skipping {name!r} — post appears to be {age_match.group()} old")
                return None

            # Skip non-English posts
            if not _is_english(post_text):
                log.info(f"Skipping {name!r} — post does not appear to be in English")
                return None

            return {
                "post_url":    post_url,
                "post_text":   post_text[:600],
                "poster_url":  profile_url,
                "poster_name": name,
            }

        # ── Tiered search strategy ────────────────────────────────────────────
        # Three tiers, each with specific keyword groups. We run searches for each
        # tier and tag every result so the dashboard can show WHY it was picked.
        # Past week → past month → past year fallback per keyword.

        # Tier 1: Watering holes — creators whose audience IS the ICP
        # Look for people posting about B2B growth, LinkedIn strategy, content systems
        _TIER1_QUERIES = [
            "founder content strategy linkedin",
            "B2B thought leadership linkedin",
            "personal brand ROI B2B",
            "linkedin content system founder",
            "video content B2B founders",
        ]

        # Tier 2: Adjacent peers — same audience, different service
        # Brand strategists, B2B copywriters, positioning coaches
        _TIER2_QUERIES = [
            "B2B brand strategy consultant",
            "copywriting B2B founders linkedin",
            "positioning founder linkedin",
            "messaging B2B agency owner",
        ]

        # Tier 3: ICP direct — founders in active pain about visibility/content
        # Look for the specific problem Authentik Studio solves
        _TIER3_QUERIES = [
            "founder linkedin not getting traction",
            "content not working B2B",
            "credibility online B2B",
            "expert founder invisible linkedin",
        ]

        # If the caller passed explicit keywords (from the UI), use them as
        # additional Tier 3 queries so custom searches still work
        extra_kws = [kw.strip() for kw in keywords if kw.strip()]
        if extra_kws:
            _TIER3_QUERIES = extra_kws[:4] + _TIER3_QUERIES[:2]

        # Allocate budget: Tier1 gets the most searches to reflect 60-70% share
        _TIER_PLAN = [
            ("watering_hole",  "Creator whose audience = your buyers",   _TIER1_QUERIES[:3]),
            ("adjacent_peer",  "Peer serving same audience, cross-pollination", _TIER2_QUERIES[:2]),
            ("icp_direct",     "Founder in active pain about content/visibility", _TIER3_QUERIES[:2]),
        ]

        all_raw: list[tuple[dict, str, str]] = []  # (result, tier_key, tier_reason)
        seen_urls:    set[str] = set()
        seen_authors: set[str] = set()

        for tier_key, tier_reason, queries in _TIER_PLAN:
            for kw in queries:
                query = f'site:linkedin.com/posts {kw}'
                log.info(f"[{tier_key}] Brave search: {query!r}")
                batch = _brave_search(query, freshness="pw")
                if not batch:
                    batch = _brave_search(query, freshness="pm")
                if not batch:
                    batch = _brave_search(query, freshness="py")

                log.info(f"  {len(batch)} raw results for {kw!r}")
                for r in batch:
                    url = r.get("url", "")
                    author_m = _re.search(r'linkedin\.com/in/([^/?]+)', url)
                    author_id = author_m.group(1).lower() if author_m else ""
                    if url not in seen_urls and (not author_id or author_id not in seen_authors):
                        seen_urls.add(url)
                        if author_id:
                            seen_authors.add(author_id)
                        all_raw.append((r, tier_key, tier_reason))

        # Fallback if all tiers returned nothing
        if not all_raw:
            log.info("All tier searches empty — trying broad fallback…")
            for r in _brave_search("linkedin.com B2B founder content visibility", freshness="py"):
                url = r.get("url", "")
                author_m = _re.search(r'linkedin\.com/in/([^/?]+)', url)
                author_id = author_m.group(1).lower() if author_m else ""
                if url not in seen_urls and (not author_id or author_id not in seen_authors):
                    seen_urls.add(url)
                    if author_id:
                        seen_authors.add(author_id)
                    all_raw.append((r, "fallback", "General B2B content audience"))

        log.info(f"Total unique raw results across all tiers: {len(all_raw)}")

        # ── Parse, filter, and attach tier metadata ───────────────────────────
        posts = []
        for r, tier_key, tier_reason in all_raw:
            p = _parse_result(r)
            if p:
                p["tier"] = tier_key
                p["tier_reason"] = tier_reason
                log.info(f"  ✓ [{tier_key}] {p['poster_name']!r} | {p['post_url'][:55]}…")
                posts.append(p)
                if len(posts) >= count * 3:  # gather extra so scoring can filter aggressively
                    break

        log.info(f"Brave Search: {len(posts)} usable posts across all tiers")

        # ── Relevance scoring — sorts by fit, flags low-relevance posts ────────
        if posts:
            try:
                from config import YOUR_OFFERING
                posts = _score_post_relevance(posts, YOUR_OFFERING)
                low = sum(1 for p in posts if p.get("low_relevance"))
                log.info(f"Relevance filter: {len(posts)-low} relevant, {low} flagged as low-relevance")
            except Exception as e:
                log.warning(f"Could not score relevance: {e}")

        return posts

    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="ignore")[:300]
        log.warning(f"Brave API HTTP {e.code} error: {body}")
        return []
    except Exception as e:
        log.warning(f"Brave post search error: {e}", exc_info=True)
        return []


def scan_feed_for_posts(icp_keywords: list[str], count: int = 10) -> list[dict]:
    """
    Scan LinkedIn feed for posts matching ICP keywords.
    Returns list of: {post_url, post_text, poster_url, poster_name}
    """
    from playwright.sync_api import sync_playwright
    from linkedin_client import PROFILE_DIR
    import os

    state_file = os.path.join(PROFILE_DIR, "state.json")
    if not os.path.exists(state_file):
        raise RuntimeError("LinkedIn session not found. Run Connect first to log in.")

    posts = []

    pw = sync_playwright().start()
    try:
        browser = pw.chromium.launch(headless=True, args=_PLAYWRIGHT_ARGS)
        context = browser.new_context(
            storage_state=state_file,
            user_agent=_USER_AGENT,
            viewport={"width": 1440, "height": 900},
            locale="en-AU",
            timezone_id="Australia/Sydney",
        )
        # Inject anti-detection patches before any page JS runs
        context.add_init_script(_ANTI_DETECT_JS)
        page = context.new_page()
        # Cap ALL Playwright operations at 15s — prevents page.evaluate() hanging forever
        page.set_default_timeout(15000)

        log.info("Scanning LinkedIn feed for relevant posts…")
        # Use domcontentloaded — LinkedIn's SPA never reaches networkidle
        page.goto("https://www.linkedin.com/feed/", wait_until="domcontentloaded", timeout=20000)
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass  # Fine — continue once DOM is ready
        time.sleep(random.uniform(2, 3))

        # Debug: log what page we actually landed on
        current_url = page.url
        try:
            page_title = page.title()
        except Exception:
            page_title = "unknown"
        log.info(f"Feed page: url={current_url}  title={page_title}")

        # Session + safety check — catches login walls, CAPTCHA, challenges
        danger_parts = ("login", "authwall", "checkpoint", "uas/", "verify",
                        "captcha", "challenge", "security")
        if any(p in current_url for p in danger_parts):
            log.error(f"⚠ LinkedIn safety wall detected: {current_url}")
            log.error("STOPPING — open LinkedIn manually, complete any challenge, then try again.")
            raise RuntimeError(f"LinkedIn session issue — landed on: {current_url}")

        # Wait for posts — just try once, no retry spam
        try:
            page.wait_for_selector('[data-urn], .feed-shared-update-v2, .occludable-update', timeout=8000)
            log.info("Feed posts detected in DOM.")
        except Exception:
            log.warning("Feed posts selector timed out — page may use different structure")

        # Scroll to load more posts (mouse wheel is more human-like than End key)
        for _ in range(4):
            page.mouse.wheel(0, random.randint(600, 1000))
            time.sleep(random.uniform(1.5, 2.5))

        # Extract posts — uses multiple selector strategies for resilience
        # LinkedIn's DOM changes frequently; we try several patterns in order
        raw_posts = page.evaluate("""() => {
            const results = [];

            // ── Strategy A: modern feed (2024-2026) ──────────────────────────
            // Posts are li items with data-urn containing "activity"
            const modernItems = document.querySelectorAll(
                'li[data-urn*="activity"], div[data-urn*="activity"], ' +
                '.occludable-update, [data-id*="urn:li:activity"]'
            );

            const tryExtract = (container) => {
                // Text: try several known selectors, fall back to full innerText
                const textSelectors = [
                    '.feed-shared-update-v2__description .break-words',
                    '.update-components-text .break-words',
                    '.attributed-text-segment-list__content',
                    '.feed-shared-text',
                    '[data-test-id="main-feed-activity-card__commentary"]',
                    '.update-components-text',
                    '.feed-shared-update-v2__description',
                ];
                let text = '';
                for (const sel of textSelectors) {
                    const el = container.querySelector(sel);
                    if (el && el.innerText.trim().length > 30) {
                        text = el.innerText.trim();
                        break;
                    }
                }

                // Name: try actor name selectors
                const nameSelectors = [
                    '.update-components-actor__name span[aria-hidden="true"]',
                    '.update-components-actor__name',
                    '.feed-shared-actor__name',
                    '.update-components-actor__title span[aria-hidden="true"]',
                    '.app-aware-link[href*="/in/"] span[aria-hidden="true"]',
                ];
                let name = '';
                for (const sel of nameSelectors) {
                    const el = container.querySelector(sel);
                    if (el && el.innerText.trim()) {
                        name = el.innerText.trim().split('\\n')[0].trim();
                        break;
                    }
                }

                // Profile URL
                const profileSelectors = [
                    '.update-components-actor__meta-link',
                    '.update-components-actor__image a',
                    'a[href*="/in/"]',
                ];
                let profileHref = '';
                for (const sel of profileSelectors) {
                    const el = container.querySelector(sel);
                    if (el && el.href && el.href.includes('/in/')) {
                        profileHref = el.href.split('?')[0];  // strip tracking params
                        break;
                    }
                }

                // Post permalink (from timestamp link)
                let postHref = '';
                const timeLink = container.querySelector(
                    'a[href*="/feed/update/"], a[href*="activity:"]'
                );
                if (timeLink) postHref = timeLink.href.split('?')[0];

                return { text, name, profileHref, postHref };
            };

            // Try modern items first
            for (const item of modernItems) {
                const { text, name, profileHref, postHref } = tryExtract(item);
                if (text.length > 50 && name) {
                    results.push({ text, name, profileUrl: profileHref, postUrl: postHref });
                }
                if (results.length >= 30) break;
            }

            // ── Strategy B: classic feed structure (fallback) ─────────────
            if (results.length === 0) {
                const classicItems = document.querySelectorAll('.feed-shared-update-v2');
                for (const item of classicItems) {
                    const { text, name, profileHref, postHref } = tryExtract(item);
                    if (text.length > 50 && name) {
                        results.push({ text, name, profileUrl: profileHref, postUrl: postHref });
                    }
                    if (results.length >= 30) break;
                }
            }

            // ── Strategy C: broadest fallback — grab any substantial text block ──
            if (results.length === 0) {
                const allLinks = document.querySelectorAll('a[href*="/in/"]');
                const seen = new Set();
                for (const link of allLinks) {
                    const href = link.href.split('?')[0];
                    if (!href.includes('/in/') || seen.has(href)) continue;
                    seen.add(href);
                    const container = link.closest('div[data-id], li, article') || link.parentElement;
                    if (!container) continue;
                    const text = container.innerText.trim();
                    const name = link.innerText.trim().split('\\n')[0].trim();
                    if (text.length > 100 && name.length > 2) {
                        results.push({ text: text.slice(0, 600), name, profileUrl: href, postUrl: '' });
                    }
                    if (results.length >= 20) break;
                }
            }

            return results;
        }""")

        log.info(f"Raw posts extracted from feed (DOM selectors): {len(raw_posts)}")

        # ── Strategy D: raw page text → Claude parses posts ───────────────
        # This is the nuclear fallback when all DOM selectors fail (LinkedIn layout changes)
        if len(raw_posts) == 0:
            log.info("DOM selectors found nothing — trying raw text extraction via Claude…")
            try:
                page_text = page.inner_text("body", timeout=10000)
                # Trim to a reasonable size for the API
                page_text = page_text[:6000]
                log.info(f"Raw page text length: {len(page_text)} chars")

                if len(page_text) > 200:
                    import anthropic
                    from config import ANTHROPIC_API_KEY
                    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
                    resp = client.messages.create(
                        model="claude-haiku-4-5-20251001",
                        max_tokens=1500,
                        messages=[{"role": "user", "content": f"""This is raw text scraped from a LinkedIn feed page.
Extract up to 10 LinkedIn posts from this text. For each post return a JSON array like:
[{{"name": "Person Name", "text": "post content...", "profileUrl": ""}}]

Only include posts with actual meaningful content (skip ads, "Promoted", navigation text etc.).
If you can't find any posts, return [].
Return ONLY the JSON array, nothing else.

PAGE TEXT:
{page_text}"""}]
                    )
                    import json as _json
                    parsed = _json.loads(resp.content[0].text.strip())
                    if isinstance(parsed, list):
                        raw_posts = parsed
                        log.info(f"Claude extracted {len(raw_posts)} posts from raw text")
            except Exception as e:
                log.warning(f"Raw text extraction failed: {e}")

        # Filter by ICP keywords (if no keywords given, accept all posts)
        keywords_lower = [k.lower() for k in icp_keywords]
        for p in raw_posts:
            text_lower = (p.get("text") or "").lower()
            name = p.get("name") or ""
            profile_url = p.get("profileUrl") or ""

            # Accept post if it matches any keyword, or if no keywords were given
            if not keywords_lower or any(k in text_lower for k in keywords_lower):
                posts.append({
                    "post_url":    p.get("postUrl") or profile_url,
                    "post_text":   p.get("text", "")[:600],
                    "poster_url":  profile_url,
                    "poster_name": name,
                })
            if len(posts) >= count:
                break

        # Persist refreshed session cookies so they don't go stale
        context.storage_state(path=state_file)
        browser.close()
        log.info(f"Found {len(posts)} relevant posts.")

    except Exception as e:
        log.error(f"Feed scan error: {e}")
    finally:
        try:
            pw.stop()
        except Exception:
            pass

    return posts[:count]


def post_comment(poster_url: str, comment_text: str, post_url: str = "") -> bool:
    """
    Navigate to a post and submit the comment.
    If post_url is given (from Brave search), navigates directly to it.
    Otherwise falls back to poster's recent-activity page.
    Returns True if successful.
    """
    from playwright.sync_api import sync_playwright
    from linkedin_client import PROFILE_DIR
    import os

    state_file = os.path.join(PROFILE_DIR, "state.json")
    if not os.path.exists(state_file):
        raise RuntimeError("LinkedIn session not found.")

    posted = False
    context = None
    pw = sync_playwright().start()
    try:
        browser = pw.chromium.launch(headless=True, args=_PLAYWRIGHT_ARGS)
        context = browser.new_context(
            storage_state=state_file,
            user_agent=_USER_AGENT,
            viewport={"width": 1440, "height": 900},
            locale="en-AU",
            timezone_id="Australia/Sydney",
        )
        # Inject anti-detection patches before any page JS runs
        context.add_init_script(_ANTI_DETECT_JS)
        page = context.new_page()
        page.set_default_timeout(15000)

        # Navigate directly to the post if we have a URL, otherwise use recent-activity
        if post_url and "linkedin.com/posts/" in post_url:
            target_url = post_url
            log.info(f"Navigating to post directly: {post_url[:80]}…")
        else:
            target_url = poster_url.rstrip("/") + "/recent-activity/all/"
            log.info(f"Navigating to recent activity: {target_url[:80]}…")

        page.goto(target_url, wait_until="domcontentloaded", timeout=20000)
        try:
            page.wait_for_load_state("networkidle", timeout=5000)
        except Exception:
            pass
        time.sleep(random.uniform(2, 4))

        current_url = page.url
        # Session check — also catches CAPTCHA / challenge pages
        danger_parts = ("login", "authwall", "checkpoint", "uas/", "captcha",
                        "challenge", "verify", "security")
        if any(p in current_url for p in danger_parts):
            log.error(f"⚠ LinkedIn safety wall detected: {current_url}")
            log.error("STOPPING comment posting — do not retry immediately.")
            log.error("Open LinkedIn in your browser manually, complete any challenge, then try again tomorrow.")
            raise RuntimeError(f"LinkedIn safety check: {current_url}")

        # Random pre-action pause — humans don't immediately start typing
        time.sleep(random.uniform(1.5, 4))

        # Scroll down naturally before interacting (human reads the post first)
        page.mouse.wheel(0, random.randint(300, 600))
        time.sleep(random.uniform(1, 2.5))

        # Find and click the comment button / input field
        # Try comment input first (direct post pages show the text area)
        comment_input = page.query_selector(
            '.comments-comment-box .ql-editor[contenteditable], '
            '.comments-comment-texteditor .ql-editor[contenteditable], '
            '[data-placeholder*="comment" i][contenteditable]'
        )
        if comment_input:
            comment_input.click()
            time.sleep(0.5)
        else:
            # Fall back to clicking a comment button first
            comment_btn = page.query_selector(
                '[aria-label*="comment" i], '
                'button[data-control-name="comment"], '
                '.comment-button, .social-actions__button--comment'
            )
            if not comment_btn:
                log.warning(f"Could not find comment button on {target_url}")
                return False
            comment_btn.click()
            time.sleep(random.uniform(1, 2))
            comment_input = page.query_selector(
                '.ql-editor[contenteditable], .comments-comment-box__editor'
            )

        if not comment_input:
            log.warning(f"Comment box not found on {target_url}")
            return False

        comment_input.click()
        time.sleep(random.uniform(0.5, 1.5))

        # Type with human-like variation: random speed, occasional micro-pauses
        for char in comment_text:
            page.keyboard.type(char, delay=random.randint(30, 120))
            # 5% chance of a natural thinking pause mid-sentence
            if random.random() < 0.05:
                time.sleep(random.uniform(0.3, 1.2))

        time.sleep(random.uniform(1.5, 3))

        # Submit — try button first, fall back to keyboard
        submit_btn = page.query_selector(
            'button.comments-comment-box__submit-button, '
            '[data-control-name="submit_comment"], '
            '[data-control-name="submit"]'
        )
        if submit_btn:
            submit_btn.click()
        else:
            page.keyboard.press("Control+Enter")

        time.sleep(random.uniform(2, 3))
        log.info(f"Comment posted on {target_url}")
        posted = True

    except Exception as e:
        log.error(f"Comment posting error: {e}")
        posted = False
    finally:
        # Always save cookies — even on failure, the session was refreshed
        if context:
            try:
                context.storage_state(path=state_file)
            except Exception:
                pass
        try:
            pw.stop()
        except Exception:
            pass

    return posted


def cmd_scan_posts(icp_description: str = "", count: int = 5):
    """
    CLI command: scan for posts and queue AI-generated comments for review.

    Smart Scan mode (default): fetches the best 5 posts across all three
    engagement tiers, scores them, drops low-relevance ones, and pre-generates
    a comment for each — ready to approve with one click in the Engage tab.
    The focus is QUALITY over quantity. 5 sharp comments beat 15 mediocre ones.
    """
    from state_manager import load_state, save_state, add_pending_comment
    from config import YOUR_OFFERING

    state = load_state()

    # Keywords from caller (e.g. user typed custom terms in the dashboard)
    # Fall back to empty list — the tiered strategy uses its own curated queries
    if icp_description:
        keywords = [w for w in icp_description.lower().split() if len(w) >= 2]
    else:
        keywords = []

    # ── Fetch posts via tiered Brave Search ─────────────────────────────────
    log.info("Smart Scan: searching for high-value posts across engagement tiers…")
    # Fetch generously so we have room to filter; top 5 will be selected after scoring
    all_posts = _search_for_posts(keywords, count=25)

    # ── Fallback: headless feed scan if Brave returns nothing ────────────────
    if not all_posts:
        log.info("Brave search returned nothing — falling back to headless feed scan…")
        # Pass tier info manually for the feed-scan fallback
        raw = scan_feed_for_posts(keywords or ["founder", "b2b", "content", "linkedin"], count=15)
        for p in raw:
            p.setdefault("tier", "fallback")
            p.setdefault("tier_reason", "LinkedIn feed scan")
        all_posts = raw

    if not all_posts:
        log.info("No matching posts found — try different keywords or scan again later.")
        return

    # ── Dedup: skip already-commented or already-queued posts ───────────────
    posted_post_urls   = {c.get("post_url")   for c in state.get("posted_comments", [])}
    posted_poster_urls = {c.get("poster_url") for c in state.get("posted_comments", [])}
    pending_post_urls  = {c.get("post_url") for c in state.get("pending_comments", [])
                          if c.get("status") in ("pending", "approved", "skipped")}

    fresh_posts = []
    for post in all_posts:
        if post["post_url"] in posted_post_urls:
            log.info(f"Skip {post['poster_name']} — already commented on this post.")
            continue
        if post["post_url"] in pending_post_urls:
            log.info(f"Skip {post['poster_name']} — already in review queue.")
            continue
        if post["poster_url"] in posted_poster_urls:
            log.info(f"Skip {post['poster_name']} — already commented on their content.")
            continue
        fresh_posts.append(post)

    if not fresh_posts:
        log.info("All found posts already commented or queued — nothing new to add.")
        return

    # ── Smart Pick: only high-relevance posts, strict quality bar ────────────
    # Posts are already sorted by relevance_score (descending) from _score_post_relevance.
    # We NEVER fall back to low-relevance posts — better to queue fewer, better comments.
    target = count  # default = 5 (Smart Scan target)

    MIN_SCORE = 6  # must score at least 6/10 to be considered
    good = [p for p in fresh_posts
            if not p.get("low_relevance") and p.get("relevance_score", 5) >= MIN_SCORE]

    if not good:
        log.info("Smart Scan: no posts met quality bar (score >= 6). Nothing queued — try again tomorrow.")
        return

    selected = good[:target]
    log.info(f"Smart Pick: {len(fresh_posts)} fetched → {len(good)} passed quality bar → {len(selected)} selected")

    tier_counts = {}
    for p in selected:
        t = p.get("tier", "unknown")
        tier_counts[t] = tier_counts.get(t, 0) + 1
    log.info(f"Smart Pick selected {len(selected)} posts: {tier_counts}")

    # ── Generate comments and queue for approval ─────────────────────────────
    queued = 0
    for post in selected:
        tier_label = {
            "watering_hole": "Tier 1 — Watering hole",
            "adjacent_peer":  "Tier 2 — Adjacent peer",
            "icp_direct":     "Tier 3 — ICP direct",
            "fallback":       "Feed scan",
        }.get(post.get("tier", ""), "Scanned")

        log.info(
            f"[{tier_label}] Generating comment for {post['poster_name']!r} "
            f"(score {post.get('relevance_score', '?')}/10)…"
        )
        comment = generate_comment(post["post_text"], post["poster_name"], YOUR_OFFERING)
        if comment:
            add_pending_comment(
                state,
                post_url          = post["post_url"],
                post_text         = post["post_text"],
                poster_url        = post["poster_url"],
                poster_name       = post["poster_name"],
                suggested_comment = comment,
                relevance_score   = post.get("relevance_score", 5),
                low_relevance     = post.get("low_relevance", False),
                tier              = post.get("tier", ""),
                tier_reason       = post.get("tier_reason", ""),
            )
            queued += 1
        time.sleep(random.uniform(1, 2))

    save_state(state)
    log.info(
        f"Smart Scan complete. Queued {queued} comments for your review in the Engage tab. "
        f"Approve the ones you like — they post on the next Post Comments run."
    )


def cmd_post_approved_comments():
    """CLI command: post all approved comments (max MAX_COMMENTS_PER_DAY)."""
    from state_manager import load_state, mark_comment

    state = load_state()
    today_count = _count_comments_today(state)

    if today_count >= MAX_COMMENTS_PER_DAY:
        log.info(f"Already posted {today_count} comments today. Limit is {MAX_COMMENTS_PER_DAY}.")
        return

    approved = [c for c in state.get("pending_comments", []) if c.get("status") == "approved"]
    if not approved:
        log.info("No approved comments to post. Review and approve in the Engage tab.")
        return

    # Cap per RUN (not per day) — never post all at once; spread naturally through day
    remaining_today = MAX_COMMENTS_PER_DAY - today_count
    per_run_cap     = min(MAX_COMMENTS_PER_RUN, remaining_today)

    if per_run_cap <= 0:
        log.info(f"Already posted {today_count} comments today. Limit is {MAX_COMMENTS_PER_DAY}.")
        return

    log.info(f"Will post up to {per_run_cap} comment(s) this run "
             f"({today_count} posted today, daily limit {MAX_COMMENTS_PER_DAY}).")

    posted = 0
    for c in approved:
        if posted >= per_run_cap:
            log.info(f"Per-run cap ({MAX_COMMENTS_PER_RUN}) reached — remaining approved comments will post next run.")
            break
        text = c.get("final_text") or c.get("suggested_comment", "")
        if not text:
            continue

        log.info(f"Posting comment on {c['poster_name']}'s post…")
        success = post_comment(c["poster_url"], text, post_url=c.get("post_url", ""))
        if success:
            mark_comment(state, c["id"], "posted", text)
            posted += 1
            log.info(f"✓ Posted comment {posted}/{per_run_cap} this run")
            if posted < per_run_cap:
                # Variable gap: 4-12 min — wide range looks human
                gap = random.uniform(MIN_GAP_SECONDS, MAX_GAP_SECONDS)
                log.info(f"Waiting {gap/60:.1f} min before next comment…")
                time.sleep(gap)
        else:
            log.warning(f"Failed to post comment on {c['poster_name']}")

    log.info(f"Done — {posted} comment(s) posted this run, {today_count + posted} total today.")
